apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: m1yrjeg97-go 
  janus-idp.io/tekton: m1yrjeg97-go
  backstage.io/kubernetes-id: m1yrjeg97-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: m1yrjeg97-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml